
language: objective-c  #1
osx_image: xcode10.2.1 #2
xcode_project: ESSDynamicForm.xcodeproj #3
xcode_scheme: ESSDynamicForm #4
xcode_sdk: iphonesimulator12.2 #5

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
