# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
  # Add a lane in Fastfile
desc "Run lint"
lane :lint do
  swiftlint(
    mode: :lint,
    executable: "Pods/SwiftLint/swiftlint",
    reporter: "html",
    output_file: "swiftlint-results.html",
    ignore_exit_status: true
  )
end
desc "Scan coverage local"
  lane :scan_local do
    scan(clean: true, scheme: "ESSDynamicForm", code_coverage: true, device: "iPad Pro (10.5-inch) (11.4)", derived_data_path: "./DerivedData", output_directory: "./sonar-reports")
    slather(html: true, workspace: "./ESSDynamicForm.xcworkspace", input_format: "profdata", jenkins: true, verbose: true, scheme: "ESSDynamicForm", build_directory: "./DerivedData", output_directory: "./local-reports", proj: "./ESSDynamicForm.xcodeproj")
  end
end
